# =============================================================================
# Application Infrastructure - test Environment
# =============================================================================
# Generated by scripts/setup-application-terraform.sh
# Customize these values for your test environment
# =============================================================================

project_name = "my-project"
environment  = "test"
aws_region   = "us-east-1"
github_repo  = "your-org/your-repo" # TODO: Update with your GitHub repo

# ECR Repository (created by bootstrap)
ecr_repository_name = "my-project" # Must match bootstrap configuration

# Lambda Configuration
lambda_memory_size  = 512
lambda_timeout      = 30
lambda_architecture = "arm64" # or "x86_64"

# API Gateway (optional - Lambda Function URLs are used by default)
enable_api_gateway = false

# Additional tags
additional_tags = {
  CostCenter = "engineering"
  Team       = "platform"
}
